### ISSUE TITLE
Epic #2 - Design and Assets

### ISSUE THREAD

**Issue by secretfire-z** [secretfirecreative/sfc.github.io#3]

**Comment by secretfire-z** [comment]
- [ ]     Task: Design the layout of the home page.
- [ ]     Task: Create raster image in GIMP to use as foundation for background animation.
- [ ]     Task: Create layers and masks as appropriate to set up animation frames.
- [ ]     Task: Create assets to animate across background image.
- [ ]     Task: Create animation frames to be converted into video loop.
- [ ]     Task: Create video loop for the background animation.
- [ ]     Task: Prepare any graphics or additional media to be used on the page.
