### ISSUE TITLE
Epic #2 - Design and Assets

### ISSUE THREAD

**Issue by secretfire-z** [secretfirecreative/sfc.github.io#5]
The focus here is on the visual and aesthetic aspects of the project. Tasks will include designing a wireframe for the homepage to provide a visual guide for the application layout. It also involves the creation or procurement of digital assets, such as a background video, icons, logos, and any images needed. These assets should be optimized for web use to ensure they do not adversely affect the website's performance.

**Comment by secretfire-z** [comment]
- [ ]     Task 2.1: Design the layout of the home page using a wireframe/mockup.
- [x]     Task 2.2: Create raster image in GIMP to use as foundation for background animation.
- [x]     Task 2.3: Create layers and masks as appropriate to set up animation frames.
- [x]     Task 2.4: Create assets to animate across background image.
- [ ]     Task 2.5: Create animation frames to be converted into video loop.
- [ ]     Task 2.6: Create video loop for the background animation.
- [ ]     Task 2.7: Create other graphic assets like logos, icons, or images that are required for the MVP.
