### ISSUE TITLE
Epic #5 - Development - Backend

### ISSUE THREAD

**Issue by secretfire-z** [secretfirecreative/sfc.github.io#8]
In this epic, the backend services of the application are developed. Utilizing C# and .NET, a web API will be created to manage any dynamic content or backend processes needed by the frontend. The API will be structured with appropriate routing, and Cross-Origin Resource Sharing (CORS) will be configured to ensure the frontend can successfully interact with the backend. The backend will also be prepped for deployment on Azure, including any necessary configuration for services like Azure App Service.

**Comment by secretfire-z** [comment]
- [ ]     Task 5.1: Use the .NET CLI to create a new .NET Web API project.
- [ ]     Task 5.2: Set up basic routing and controllers in the .NET project.
- [ ]     Task 5.3: Create a simple API endpoint to serve dynamic content for the frontend if required.
- [ ]     Task 5.4: Configure CORS in the .NET project to allow the Angular frontend to communicate with the backend.
- [ ]     Task 5.5: Set up Azure resources (like App Service) for backend hosting.
